/**
 * CruiseUX Mod — decision-framed UX research, ideation, specification, and review.
 *
 * Commands:
 *   /ux-frame <topic>               — frame user/context/job/decision/validation
 *   /ux-research <topic>            — structured research brief
 *   /ux-interview <topic>           — adaptive UX interview with discovery, decision, or research-protocol modes
 *   /ux-ideate <topic>              — multi-concept generation with tradeoffs
 *   /ux-spec <topic>                — UX specification + prototype/test plan synthesis
 *   /ux-review <topic-or-path>      — decision-readiness review for UX artifacts
 *   /ux-cruise [auto|loop] <topic>  — full pipeline with gates by default, optional revision loop
 */

const COMMAND_DEFS = [
  {
    id: "ux-frame",
    description: "Frame a UX/UI effort around user, context, job, decision, hypotheses, and validation criteria",
    args: "<topic>",
    build: (topic) => buildFramePrompt(topic),
  },
  {
    id: "ux-research",
    description: "UX/UI research brief — competitive, domain, user, workflow, and technical research",
    args: "<topic>",
    build: (topic) => buildResearchPrompt(topic),
  },
  {
    id: "ux-interview",
    description: "Adaptive UX interview for early discovery, decision-focused prototype planning, or user research protocol design",
    args: "<topic>",
    build: (topic) => buildInterviewPrompt(topic),
  },
  {
    id: "ux-ideate",
    description: "Generate multiple UX concepts with hypotheses, tradeoffs, and ASCII wireframes",
    args: "<topic>",
    build: (topic) => buildIdeatePrompt(topic),
  },
  {
    id: "ux-spec",
    description: "Synthesize a UX spec with scenarios, validation criteria, prototype scope, and usability-test plan",
    args: "<topic>",
    build: (topic) => buildSpecPrompt(topic),
  },
  {
    id: "ux-review",
    description: "Review UX research/spec/prototype plans for decision-readiness before build or test",
    args: "<topic-or-path>",
    build: (topic) => buildReviewPrompt(topic),
  },
  {
    id: "ux-cruise",
    description: "Full UX pipeline: frame → research → adaptive interview → ideate → spec/test plan → review. Use 'auto' to skip gates. Use 'loop' to enable revision loop (max 3 iterations).",
    args: "[auto|loop] <topic>",
    build: (raw) => buildCruisePrompt(raw),
  },
];

function buildFramePrompt(topic) {
  return [
    "# UX Decision Frame",
    "",
    `Topic: ${topic}`,
    "",
    "Frame this UX/UI effort before research, ideation, or specification work. Keep it concise and decision-oriented.",
    "",
    "## Output format",
    "Produce a decision frame with these sections:",
    "",
    "1. **User** — who is the primary user? Include secondary users only if they change the UX decision.",
    "2. **Context** — where/when does this happen? Device, environment, workflow pressure, business/domain setting if relevant.",
    "3. **Job-to-be-done** — what is the user trying to accomplish in plain language?",
    "4. **Decision Needed** — what product/UX decision should this work make possible?",
    "5. **Known Evidence** — facts already known; cite sources if from web/research/docs.",
    "6. **Assumptions** — beliefs not yet proven.",
    "7. **Risks** — usability, safety, technical, compliance, trust, or workflow risks.",
    "8. **Hypotheses** — 2-4 testable UX hypotheses.",
    "9. **Validation Criteria** — what evidence would validate, partially validate, or invalidate each hypothesis?",
    "10. **Smallest Useful Prototype** — the minimal prototype needed to test the decision, not the full product.",
    "",
    "## Rules",
    "- Separate evidence from assumptions.",
    "- Make the decision explicit; do not frame work as generic exploration unless the decision truly is unknown.",
    "- If core context is missing, ask only the questions that materially change the next step.",
    "- Respond in the conversation language unless writing a shared artifact section; shared artifact text should be English.",
  ].join("\n");
}

function buildResearchPrompt(topic) {
  return [
    "# UX Research Brief",
    "",
    `Topic: ${topic}`,
    "",
    "Conduct structured UX/UI research and produce a decision-oriented research brief.",
    "",
    "## 1. Scope and decision frame",
    "- Identify product domain, target users, context, job-to-be-done, and decision needed.",
    "- If these are unclear, ask before doing broad research.",
    "",
    "## 2. Competitive / prior-art research",
    "- Search for existing products, tools, or UX patterns in the same domain.",
    "- Find competitor flows, industry conventions, risks, and gaps.",
    "- If a URL is blocked, use available search/fetch alternatives or the `insane-search` skill if installed.",
    "- For regulated, safety-critical, or security-sensitive products, include domain evidence and compliance/security constraints where relevant.",
    "- Cite all source URLs.",
    "",
    "## 3. User and workflow research",
    "- Identify primary users and real-world workflow before/during/after use.",
    "- Note environmental constraints: mobile vs desktop, offline needs, protective gear, one-handed use, time pressure, interruptions.",
    "- Capture edge cases and failure states that could break the workflow.",
    "",
    "## 4. Technical and platform constraints",
    "- Identify platform targets and integration/device constraints.",
    "- Separate implementation constraints from product/UX constraints.",
    "",
    "## 5. Output format",
    "Produce a structured brief with:",
    "- **Domain & Users** — who, what, context",
    "- **Decision Needed** — the product/UX decision this research should inform",
    "- **Competitive Landscape** — existing tools, patterns, gaps, URLs",
    "- **User Workflow** — steps, pain points, environmental constraints",
    "- **Technical / Regulatory Constraints** — platform, integration, device, safety, compliance",
    "- **Evidence** — source-backed findings only",
    "- **Assumptions** — plausible but unproven beliefs",
    "- **Risks** — UX/product/technical/safety risks",
    "- **Open Questions** — questions needing user/stakeholder input",
    "- **UX Implications** — 3-5 findings that should shape the prototype",
    "",
    "## 6. Artifact preservation",
    "- If this research belongs to a concrete project/prototype, create or use that project's `docs/search/` directory and save Markdown research artifacts with source URLs.",
    "- Preserve synthesized findings and important source-specific notes; do not leave useful research only in chat.",
    "- If the active project or save path is unclear, ask where to save instead of guessing.",
    "- If the user explicitly says not to write files, only provide the chat brief.",
    "",
    "Language: respond in the conversation language. Cite web-sourced claims with URLs.",
  ].join("\n");
}

function buildInterviewPrompt(topic) {
  return [
    "# Adaptive UX Interview",
    "",
    `Topic: ${topic}`,
    "",
    "Run an adaptive UX interview that chooses the right clarification mode for the user's situation. This command is not only for interviewing end users; it can also clarify an early idea, a project brief, or a prototype/test decision.",
    "",
    "## Core rules",
    "- Ask ONE question at a time. Never batch questions.",
    "- Use plain-language questions. Do not expose method jargon unless the user asks.",
    "- Prefer a short recommendation before asking when the likely direction is clear.",
    "- Use AskUserQuestion when available, with 2-4 practical options plus free-text.",
    "- Classify answers internally as confirmed, assumed, risk, decision, deferred, or test later.",
    "- Stop asking when the remaining unknown would be learned faster from a prototype, usability test, or research task than from more stakeholder answers.",
    "- Use the conversation language for discussion; shared artifacts should be in English unless the user asks otherwise.",
    "",
    "## Step 1: Route the interview mode",
    "Choose one of these modes based on the topic and conversation context. If the mode is obvious, state it and proceed. If not obvious, ask exactly one mode-selection question.",
    "",
    "### Mode A — Discovery Interview",
    "Use when the user has a new idea, thin context, or a broad product direction that needs shaping into a clearer UX/product brief.",
    "",
    "Goal: move from idea fog to a usable brief: user, situation, problem, workflow, constraints, and success signal.",
    "",
    "Plain-language question ladder:",
    "1. Who is this for?",
    "2. When or where does the problem happen?",
    "3. What do they do today instead?",
    "4. What is painful, slow, risky, confusing, or missing?",
    "5. What outcome should feel better after this exists?",
    "6. What constraints or non-goals matter?",
    "7. How would we know the first version worked?",
    "",
    "Output: Discovery Brief with user, context, current workaround, friction, desired outcome, constraints, non-goals, success signal, and next artifact recommendation.",
    "",
    "### Mode B — Decision Trace",
    "Use when project context already exists and the user needs to decide what to specify, prototype, test, defer, or compare next.",
    "",
    "Goal: turn project context into decision-ready prototype/test planning. Internally combine task analysis, cognitive walkthrough-style step reasoning, assumption mapping, hypothesis-driven design, and lightweight decision logging.",
    "",
    "User-facing questions must stay simple. Ask things like:",
    "- What should this prototype help you decide first?",
    "- Where could this flow go wrong?",
    "- What can we decide now, and what should we test later?",
    "- What would a user need to understand or do without explanation?",
    "",
    "Internal trace checklist:",
    "- Actor — who acts?",
    "- Trigger — what starts the flow?",
    "- Object — what is being selected, edited, reviewed, or created?",
    "- Action — what does the user do?",
    "- Feedback — how does the system respond?",
    "- State change — what changes after the action?",
    "- Failure point — where could the user make a harmful or confusing mistake?",
    "- Recovery — how does the user recover?",
    "- Handoff — what happens after this flow?",
    "",
    "Decision Trace ledger:",
    "- **Confirmed** — known enough to use",
    "- **Assumed** — plausible but unproven",
    "- **Risk** — could break usability, trust, safety, business outcome, or implementation",
    "- **Decision** — a choice now made or needed",
    "- **Deferred** — intentionally out of current scope",
    "- **Test later** — better learned through prototype/research than more questions",
    "",
    "Output: Decision Trace Brief with decision needed, workflow trace, blockers, ledger, smallest useful prototype, observable behaviors, success/failure signals, and next test/spec step.",
    "",
    "### Mode C — User Research Protocol",
    "Use when the user wants to interview real users, run a usability test, or prepare research questions/tasks.",
    "",
    "Goal: create a non-leading research or usability-test protocol, not a product-owner clarification session.",
    "",
    "Clarify only what is needed to design the protocol:",
    "- Research objective",
    "- Participant profile",
    "- Scenario or task mission",
    "- What behavior/data to capture",
    "- What not to reveal to participants",
    "- Success/failure or analysis criteria",
    "",
    "Output: User Research Protocol with objective, participant profile, session structure, non-leading questions, task missions, behavioral data to capture, qualitative prompts, analysis plan, and ethical/safety notes if relevant.",
    "",
    "## Step 2: Run the selected mode",
    "For each round:",
    "1. Briefly state your current understanding in plain language.",
    "2. State the next missing piece or decision blocker.",
    "3. Ask one easy-to-answer question with practical options.",
    "4. After the answer, update the brief/ledger/protocol for the selected mode.",
    "5. Decide whether to ask one more question, stop with a usable output, or move the unknown to test later.",
    "",
    "## Stop conditions",
    "Stop interviewing when one of these is true:",
    "- The user asks to stop, build, ideate, or write the spec.",
    "- The remaining unknowns are better tested than answered.",
    "- You have enough to produce the selected output artifact.",
    "- More questions would not change scope, flow, prototype, validation criteria, or research plan.",
    "",
    "## Completion output",
    "Produce one concise artifact based on the selected mode:",
    "- Discovery Interview → Discovery Brief",
    "- Decision Trace → Decision Trace Brief + Validation Contract",
    "- User Research Protocol → Research / Usability Test Protocol",
    "",
    "Always include:",
    "- Mode used and why",
    "- Confirmed decisions",
    "- Assumptions and risks",
    "- Open questions",
    "- What to specify now",
    "- What to prototype or test later",
    "- Recommended next command: /ux-research, /ux-ideate, /ux-spec, /ux-review, or stop",
    "",
    "Do not jump to implementation. Offer to save useful artifacts to `docs/plans/` or `docs/search/` when a concrete project path is known.",
  ].join("\n");
}

function buildIdeatePrompt(topic) {
  return [
    "# UX Ideation — Multi-Concept Generation",
    "",
    `Topic: ${topic}`,
    "",
    "Generate multiple UX concepts for this topic, building on any prior decision frame, research, or interview results in the conversation.",
    "",
    "## 1. Context review",
    "- Summarize known user, context, job-to-be-done, decision needed, constraints, and validation criteria.",
    "- If there is no decision frame, create a short provisional one before ideating.",
    "- If essential context is missing, ask one clarifying question before generating concepts.",
    "",
    "## 2. Generate 3 distinct UX concepts",
    "Concepts must differ in approach, not just visual styling. Vary interaction paradigm, information density, entry point, device posture, automation level, or confirmation model.",
    "",
    "## 3. For each concept, provide",
    "- **Name** — short memorable label",
    "- **Core idea** — one sentence",
    "- **Hypothesis** — what this concept assumes will work",
    "- **What the prototype validates** — specific behavior or decision evidence",
    "- **Failure signal** — what would make this concept fail or need revision",
    "- **User flow** — 3-7 user steps",
    "- **ASCII wireframe** — rough sketch of the primary screen/state",
    "- **Strengths** — 2-3 bullets",
    "- **Weaknesses** — 2-3 bullets",
    "- **Best for** — when this approach shines",
    "",
    "## 4. Comparison table",
    "Compare concepts across criteria such as ease of use, learnability, expert efficiency, mobile fit, safety/trust, build complexity, and quality of decision evidence.",
    "",
    "## 5. Recommendation",
    "Recommend one concept or hybrid. Explain the tradeoff, first prototype scope, and first validation task.",
    "",
    "Language: respond in the conversation language. ASCII wireframes in monospace blocks.",
  ].join("\n");
}

function buildSpecPrompt(topic) {
  return [
    "# UX Specification Synthesis",
    "",
    `Topic: ${topic}`,
    "",
    "Synthesize a complete UX specification from the current conversation, including prototype scope and usability-test plan.",
    "",
    "## Input review",
    "- Review prior decision framing, research, interview, and ideation in the conversation.",
    "- If prior context is thin, list what is missing and ask for clarification before proceeding.",
    "",
    "## Output: UX Specification Document",
    "Produce the shared artifact in English using this structure:",
    "",
    "```markdown",
    "# UX Spec: {title}",
    "",
    "## 1. Overview",
    "- Product context and purpose",
    "- Target users and primary goal",
    "- Decision this spec is meant to support",
    "",
    "## 2. Evidence, Assumptions, and Open Questions",
    "| Type | Item | Source / Rationale | Impact |",
    "|------|------|--------------------|--------|",
    "",
    "## 3. UX Hypotheses",
    "| Hypothesis | Validation Criteria | Failure Signal | Decision Impact |",
    "|------------|---------------------|----------------|-----------------|",
    "",
    "## 4. User Scenarios",
    "For each scenario:",
    "- **Scenario name**",
    "- **User**",
    "- **Trigger**",
    "- **Steps**: numbered, step-by-step",
    "- **Expected outcome**",
    "- **Edge cases**",
    "- **Error handling / recovery**",
    "",
    "## 5. Validation Criteria",
    "- [ ] {testable behavior or evidence criterion}",
    "",
    "## 6. Edge Cases & Error States",
    "| Case | Trigger | System Response | User Recovery |",
    "|------|---------|-----------------|---------------|",
    "",
    "## 7. ASCII Wireframes",
    "For each key screen/state, include layout and annotations for interactive elements.",
    "",
    "## 8. Prototype Plan",
    "- Smallest useful prototype scope",
    "- Version/path suggestion, if this is a project with versioned prototypes",
    "- What is mocked vs. real",
    "- What must be validated before expanding scope",
    "",
    "## 9. Usability Test Plan",
    "- **Participants / role**",
    "- **Mission(s)**: task wording participants will see",
    "- **Behavioral data to capture**: completion, time, first click, wrong clicks, retries, route choice, etc.",
    "- **Qualitative prompts**: short post-task questions",
    "- **Edge cases to observe**",
    "- **Decision threshold**: what evidence is enough to proceed, revise, or reject",
    "",
    "## 10. Constraints & Non-Goals",
    "- Platform, technical, compliance/regulatory, safety, data, or design-system constraints",
    "- Explicit non-goals",
    "",
    "## 11. Decision Recommendation",
    "- Recommended next decision",
    "- Evidence supporting it",
    "- Tradeoffs",
    "- Next iteration",
    "```",
    "",
    "## Rules",
    "- Separate evidence, assumptions, open questions, and decisions clearly.",
    "- For regulated, safety-critical, security, or business-critical claims, cite sources and separate evidence from assumptions.",
    "- Use ASCII wireframes first; do not jump to high fidelity.",
    "- For early prototypes, prefer standalone HTML/CSS/JS unless the user or repo conventions say otherwise.",
    "- Offer to save the spec to the project's `docs/plans/` directory.",
    "- Use the conversation language for discussion; shared artifacts should be in English unless the user asks otherwise.",
  ].join("\n");
}

function buildReviewPrompt(topic) {
  return [
    "# UX Decision-Readiness Review",
    "",
    `Topic or artifact path: ${topic}`,
    "",
    "Review the referenced UX research, plan, spec, prototype plan, or current conversation for decision-readiness. This is a review/check command, not a generator command.",
    "",
    "## Review process",
    "1. If a file path is provided, read the file before reviewing. If the path is unclear, ask for the path or artifact.",
    "2. Identify what artifact type is being reviewed: research brief, interview spec, ideation output, UX spec, prototype plan, test plan, or mixed context.",
    "3. Check whether the artifact can support a product/UX decision without hidden assumptions.",
    "",
    "## Rubric",
    "Score each item as Pass / Partial / Missing:",
    "",
    "- **Decision needed** is explicit.",
    "- **User, context, and job-to-be-done** are clear.",
    "- **Evidence, assumptions, risks, and open questions** are separated.",
    "- **UX hypotheses** are testable.",
    "- **Validation criteria** are tied to observable behavior or evidence.",
    "- **Flows and interaction model** are understandable before visual polish.",
    "- **Edge cases and error/recovery states** are covered.",
    "- **Prototype scope** is the smallest useful testable scope.",
    "- **Usability test plan** captures behavioral data and qualitative feedback.",
    "- **Decision threshold** states what evidence is enough to proceed, revise, or reject.",
    "- **Artifact save paths** are clear when files should be written (`docs/search/`, `docs/plans/`, etc.).",
    "",
    "## Output format",
    "```markdown",
    "# UX Review: {title}",
    "",
    "## Verdict",
    "Ready | Needs Revision | Not Ready",
    "",
    "## Summary",
    "- {1-3 concise bullets}",
    "",
    "## Checklist",
    "| Area | Status | Notes | Required fix if not ready |",
    "|------|--------|-------|---------------------------|",
    "",
    "## Blocking Gaps",
    "- {gap}",
    "",
    "## Recommended Fixes Before Coding or Testing",
    "1. {fix}",
    "",
    "## Decision Status",
    "- Decision that can be made now: {decision or None}",
    "- Evidence still needed: {evidence}",
    "```",
    "",
    "## Rules",
    "- Be direct. Do not rubber-stamp weak artifacts.",
    "- Do not rewrite the whole artifact unless asked; identify the smallest fixes needed.",
    "- If regulated, safety-critical, security, or business-critical evidence is weak, say so explicitly.",
    "- Respond in the conversation language unless producing a shared artifact section.",
  ].join("\n");
}

function buildCruisePrompt(raw) {
  const trimmed = String(raw).trim();
  let autoMode = false;
  let loopMode = false;
  let topic = trimmed;

  const modeMatch = trimmed.match(/^(auto|loop)(?:\s+(.+))?$/i);
  if (modeMatch) {
    const mode = modeMatch[1].toLowerCase();
    const rest = String(modeMatch[2] ?? "").trim();
    const secondModeMatch = rest.match(/^(auto|loop)(?:\s+|$)/i);

    if (secondModeMatch) {
      return {
        type: "output",
        output: cruiseModeErrorText(),
      };
    }

    autoMode = mode === "auto";
    loopMode = mode === "loop";
    topic = rest;
  }

  if (!topic) {
    return {
      type: "output",
      output: commandHelp("ux-cruise"),
    };
  }

  const gateInstruction = autoMode
    ? [
        "## Gate mode: AUTO",
        "Run all pipeline stages sequentially without confirmation gates between stages.",
        "The interview stage still naturally pauses for user answers.",
        "After each non-interview stage, summarize the result in 1-3 lines and proceed.",
        "Do not ask 'should I proceed to the next stage?' between stages.",
      ].join("\n")
    : [
        "## Gate mode: PER-STAGE CONFIRMATION (default)",
        "After each stage, summarize the result and use AskUserQuestion to confirm:",
        "- Continue to next stage",
        "- Adjust and redo this stage",
        "- Skip this stage",
        "- Stop here",
        "Only proceed after user confirmation.",
      ].join("\n");

  const loopInstruction = loopMode
    ? [
        "## Loop mode: REVISION LOOP ENABLED",
        "After Stage 6 (Review), respond based on the verdict:",
        "",
        "### Ready",
        "- Stop the loop and produce the final decision-ready summary.",
        "",
        "### Needs Revision",
        "1. Identify which stage needs revision (Spec, Ideate, Interview, etc.) based on the review findings.",
        "2. Ask the user which stage to revise — recommend one based on the review findings.",
        "3. Loop back to that stage, redo it with the review feedback incorporated.",
        "4. Re-run Review on the revised output.",
        "5. Track iteration history: what changed in each iteration and why.",
        "",
        "### Not Ready",
        "Treat Not Ready as a stronger upstream rollback, not a small polish pass. First classify the root cause, then recommend the earliest stage that must be repaired:",
        "- Decision/user/context unclear → return to Stage 0: Decision Frame.",
        "- Evidence is weak or missing → return to Stage 1: Research.",
        "- User/problem/workflow is unclear → return to Stage 2: Adaptive UX Interview.",
        "- Hypotheses or success/failure signals are weak → return to Stage 3: Problem + Hypothesis + Validation Frame.",
        "- Concept direction is wrong or too narrow → return to Stage 4: Ideation.",
        "- Artifact quality/scope/edge cases/test plan are insufficient → return to Stage 5: UX Spec + Prototype/Test Plan.",
        "Ask for user confirmation before rolling back, unless the user requested auto-style execution in the same message.",
        "",
        "Maximum 3 iterations total. After 3 iterations, stop looping and produce a force-decision recommendation with current evidence, remaining risks, and the smallest next test.",
        "",
        "Loop stop conditions:",
        "- Review verdict is Ready → pipeline complete.",
        "- Review verdict remains Not Ready after rollback attempts → force-decision recommendation.",
        "- User says stop → finish with current state.",
        "- 3 iterations reached → force decision recommendation.",
        "",
        "Iteration log format:",
        "```",
        "Iteration 1: initial pipeline → Review: {verdict} → root cause: {cause} → action: revise/rollback {stage}",
        "Iteration 2: revised {stage} → Review: {verdict} → root cause: {cause} → action: revise/rollback {stage}",
        "Iteration 3: revised {stage} → Review: {verdict} → final decision recommendation",
        "```",
      ].join("\n")
    : "";

  return [
    "# UX Cruise — Decision-to-Evidence Pipeline",
    "",
    `Topic: ${topic}`,
    "",
    gateInstruction,
    loopMode ? ["", loopInstruction].join("\n") : "",
    "",
    "## Pipeline stages",
    "",
    "### Stage 0: Decision Frame",
    "Define user, context, job-to-be-done, decision needed, initial assumptions, risks, hypotheses, validation criteria, and smallest useful prototype.",
    "",
    "### Stage 1: Research",
    "Run structured UX research: competitive/prior-art, user/workflow, technical/platform, and domain/compliance/security constraints if relevant. Save durable research artifacts under `docs/search/` when a concrete project path is known. Cite source URLs.",
    "",
    "### Stage 2: Adaptive UX Interview",
    "Run `/ux-interview` as an adaptive clarification stage. Use Discovery Interview when context is thin, Decision Trace when project context exists and prototype/test decisions are needed, or User Research Protocol when the user needs questions/tasks for real participants. Ask one plain-language question at a time and stop when the next unknown is better specified, deferred, or tested.",
    "",
    "### Stage 3: Problem + Hypothesis + Validation Frame",
    "Synthesize the UX problem, hypotheses, validation criteria, failure signals, and evidence needed before ideation. This keeps concepts tied to decisions instead of opinion.",
    "",
    "### Stage 4: Ideation",
    "Generate three distinct UX concepts. For each, include hypothesis, what the prototype validates, failure signal, user flow, ASCII wireframe, strengths, weaknesses, and best-fit context. Recommend one concept or hybrid.",
    "",
    "### Stage 5: UX Spec + Prototype/Test Plan",
    "Create an English UX spec with scenarios, edge/error states, validation criteria, ASCII wireframes, smallest useful prototype scope, and usability-test plan. Offer to save under `docs/plans/`.",
    "",
    "### Stage 6: UX Review",
    "Run a decision-readiness review using the `/ux-review` rubric. Verdict must be Ready, Needs Revision, or Not Ready. Name blocking gaps and smallest fixes before coding/testing.",
    "",
    "## Execution notes",
    "- In gate mode, confirm after every stage.",
    "- In auto mode, do not ask stage-gate questions, but still ask user questions required by the interview stage.",
    "- In loop mode, gates apply AND the revision loop runs after Stage 6.",
    "- If prior conversation already contains a stage result, build on it instead of redoing from scratch.",
    "- For concrete projects, preserve research in `docs/search/` and specs/plans in `docs/plans/`.",
    "- Separate evidence, assumptions, open questions, risks, and decisions throughout.",
    "- Use the conversation language for discussion; shared docs/specs should be in English unless the user asks otherwise.",
  ].join("\n");
}

function cruiseModeErrorText() {
  return [
    "CruiseUX /ux-cruise — choose one mode only.",
    "",
    "Allowed:",
    "  /ux-cruise <topic>",
    "  /ux-cruise auto <topic>",
    "  /ux-cruise loop <topic>",
    "",
    "Not allowed:",
    "  /ux-cruise auto loop <topic>",
    "  /ux-cruise loop auto <topic>",
    "",
    "Use `auto` for one-pass execution, or `loop` for gated revision cycles. Do not combine them.",
  ].join("\n");
}

function commandHelp(commandId) {
  const helps = {
    "ux-frame": [
      "CruiseUX /ux-frame",
      "",
      "Purpose: create a compact decision frame before research, ideation, or spec work.",
      "",
      "Usage:",
      "  /ux-frame <topic>",
      "",
      "Output includes:",
      "- User, context, and job-to-be-done",
      "- Decision needed",
      "- Known evidence vs assumptions",
      "- Risks",
      "- 2-4 testable UX hypotheses",
      "- Validation criteria",
      "- Smallest useful prototype",
      "",
      "Example:",
      "  /ux-frame field technician offline inspection flow",
    ],
    "ux-research": [
      "CruiseUX /ux-research",
      "",
      "Purpose: produce a decision-oriented UX research brief with cited sources.",
      "",
      "Usage:",
      "  /ux-research <topic>",
      "",
      "Use when you need competitive, workflow, technical, platform, domain, compliance, or prior-art research.",
      "",
      "Output includes:",
      "- Domain & users",
      "- Decision needed",
      "- Competitive landscape",
      "- User workflow",
      "- Technical / regulatory constraints",
      "- Evidence, assumptions, risks, open questions",
      "- UX implications",
      "",
      "Project artifact rule: save durable research under `docs/search/` when a concrete project path is known.",
      "",
      "Example:",
      "  /ux-research AI writing assistant revision workflow",
    ],
    "ux-interview": [
      "CruiseUX /ux-interview",
      "",
      "Purpose: run an adaptive UX interview to clarify an idea, decision, or user research protocol.",
      "",
      "Usage:",
      "  /ux-interview <topic>",
      "",
      "Modes:",
      "- Discovery Interview — for new, broad, or thinly defined ideas",
      "- Decision Trace — for existing project context and prototype/spec/test decisions",
      "- User Research Protocol — for real participant interviews or usability tests",
      "",
      "Rules:",
      "- Ask one question at a time",
      "- Use plain language",
      "- Stop when remaining unknowns are better learned through prototype, test, or research",
      "",
      "Example:",
      "  /ux-interview team dashboard alert triage workflow",
    ],
    "ux-ideate": [
      "CruiseUX /ux-ideate",
      "",
      "Purpose: generate multiple distinct UX concepts before choosing a prototype direction.",
      "",
      "Usage:",
      "  /ux-ideate <topic>",
      "",
      "Output includes 3 concepts. Each concept includes:",
      "- Name and core idea",
      "- Hypothesis",
      "- What the prototype validates",
      "- Failure signal",
      "- User flow",
      "- ASCII wireframe",
      "- Strengths, weaknesses, best-fit context",
      "",
      "Example:",
      "  /ux-ideate subscription cancellation recovery flow",
    ],
    "ux-spec": [
      "CruiseUX /ux-spec",
      "",
      "Purpose: synthesize a shared English UX specification with prototype and usability-test plan.",
      "",
      "Usage:",
      "  /ux-spec <topic>",
      "",
      "Output includes:",
      "- Overview",
      "- Evidence, assumptions, open questions",
      "- UX hypotheses",
      "- User scenarios",
      "- Validation criteria",
      "- Edge cases and error states",
      "- ASCII wireframes",
      "- Prototype plan",
      "- Usability test plan",
      "- Constraints, non-goals, decision recommendation",
      "",
      "Project artifact rule: offer to save specs under `docs/plans/` when a concrete project path is known.",
      "",
      "Example:",
      "  /ux-spec B2B admin role-permission setup",
    ],
    "ux-review": [
      "CruiseUX /ux-review",
      "",
      "Purpose: review a UX artifact or current conversation for decision-readiness before build, test, or sharing.",
      "",
      "Usage:",
      "  /ux-review <topic-or-path>",
      "",
      "Verdict:",
      "  Ready | Needs Revision | Not Ready",
      "",
      "Checks include:",
      "- Decision clarity",
      "- User/context/JTBD clarity",
      "- Evidence vs assumptions separation",
      "- Testable hypotheses",
      "- Observable validation criteria",
      "- Flow understandability",
      "- Edge/error/recovery states",
      "- Prototype scope",
      "- Usability-test plan",
      "- Decision threshold",
      "",
      "Examples:",
      "  /ux-review docs/plans/v1-dashboard-alert-triage.md",
      "  /ux-review mobile checkout return-flow test plan before prototype changes",
    ],
    "ux-cruise": [
      "CruiseUX /ux-cruise",
      "",
      "Purpose: run the full CruiseUX decision-to-evidence pipeline.",
      "",
      "Usage:",
      "  /ux-cruise <topic>",
      "  /ux-cruise auto <topic>",
      "  /ux-cruise loop <topic>",
      "",
      "Modes:",
      "- Default: per-stage confirmation gates",
      "- auto: skip stage gates and run straight through; interview may still pause for needed answers",
      "- loop: gated pipeline plus Review → revise/rollback → re-review loop, max 3 iterations",
      "",
      "Invalid combinations:",
      "- Do not combine `auto` and `loop`.",
      "- `/ux-cruise auto loop <topic>` and `/ux-cruise loop auto <topic>` return an error.",
      "",
      "Pipeline:",
      "Decision Frame → Research → Adaptive UX Interview → Problem/Hypothesis/Validation Frame → Ideation → UX Spec/Test Plan → UX Review",
      "",
      "Examples:",
      "  /ux-cruise mobile checkout returns flow",
      "  /ux-cruise auto B2B onboarding permission setup",
      "  /ux-cruise loop Data Matrix scan to wound capture flow",
    ],
  };

  if (helps[commandId]) return helps[commandId].join("\n");
  return helpText();
}

function helpText() {
  return [
    "CruiseUX — commands:",
    "",
    "  /ux-frame <topic>        Decision frame: user, context, job, decision, hypotheses, validation",
    "  /ux-research <topic>     Structured UX research brief with source-backed findings",
    "  /ux-interview <topic>    Adaptive UX interview: discovery, decision trace, or research protocol",
    "  /ux-ideate <topic>       Generate 3 UX concepts with hypotheses, tradeoffs, ASCII wireframes",
    "  /ux-spec <topic>         UX spec + prototype scope + usability-test plan",
    "  /ux-review <topic/path>  Review/check decision-readiness before coding or testing",
    "  /ux-cruise [auto|loop] <topic>  Full pipeline: frame → research → interview → ideate → spec → review",
    "",
    "Default /ux-cruise mode uses per-stage gates.",
    "  /ux-cruise auto <topic>   Skip stage gates, run straight through.",
    "  /ux-cruise loop <topic>   Enable revision loop: Review → revise → re-review (max 3 iterations).",
  ].join("\n");
}

export default function activate(letta) {
  if (!letta.capabilities?.commands) return;

  const disposers = [];

  for (const def of COMMAND_DEFS) {
    disposers.push(
      letta.commands.register({
        id: def.id,
        description: def.description,
        args: def.args,
        async run(ctx) {
          const input = String(ctx.args ?? "").trim();
          if (!input || ["help", "-h", "--help"].includes(input.toLowerCase())) {
            return { type: "output", output: commandHelp(def.id) };
          }

          if (def.id === "ux-cruise") {
            const result = def.build(input);
            if (result && result.type === "output") return result;
            return { type: "prompt", content: result, systemReminder: true };
          }

          return {
            type: "prompt",
            content: def.build(input),
            systemReminder: true,
          };
        },
      }),
    );
  }

  return () => {
    for (const dispose of disposers.reverse()) dispose();
  };
}
